import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int familywithtwo = 0;
		int familywiththree = 0;
		int familywithmore = 0;
		double z;
		double avrage = 0.0;
		for (int index = 0; index < T ; index++) {
			String s = "";
			boolean boy = false;
			boolean girl = false;
			while (!(boy==true&&girl==true)) {
				avrage++; 
				z = generator.nextDouble();
				if (z >= 0.5) {
					s = s +"b "; 
					boy = true;
				} else {
					s = s + "g "; 
					girl = true; 
				}
			}
			int x = s.length()/2;
			if (x == 2) {
				familywithtwo++;
			}
           	 else if (x == 3) {
				familywiththree++;
			} else {
				familywithmore++;
			}
		}
		avrage = avrage / T;
		System.out.println("Average: " + avrage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + familywithtwo);
		System.out.println("Number of families with 3 children: " + familywiththree);
		System.out.println("Number of families with 4 or more children: " + familywithmore);
		} 
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}

